site_name: Notas musicais
repo_url: https://github.com/astropingo/notas-musicais
repo_name: astropingo/notas-musicais
edit_uri: tree/main/docs/

theme:
  name: material
  language: pt-BR
  logo: assets/astrop.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/style.css